declare module "spessasynth_core" {
    export * from "./types";
    export * from "./soundbank";
    export * from "./audio_engine/processor";
    export * from "./audio_engine/voice";
    export * from "./audio_engine/volume_envelope";
    export * from "./audio_engine/filter";
    export * from "./audio_engine/modulation_envelope";
    export * from "./audio_engine/enums";
    export * from "./audio_engine/dynamic_modulator_system";
    export * from "./audio_engine/midi_audio_channel";
    export * from "./audio_engine/soundfont_manager";
    export * from "./audio_engine/key_modifier_manager";
    export * from "./audio_engine/snapshot/channel_snapshot";
    export * from "./audio_engine/snapshot/synthesizer_snapshot";
    export * from "./audio_engine/snapshot/apply_synthesizer_snapshot";
    export * from "./sequencer/sequencer_engine";
    export * from "./sequencer/play";
    export * from "./sequencer/events";
    export * from "./sequencer/process_event";
    export * from "./sequencer/process_tick";
    export * from "./sequencer/song_control";
}
